# Generated by Django 5.1.7 on 2025-04-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='data_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
